### ISSUE TITLE
Combine svg's to sprite - apply class attribute to symbols

### ISSUE THREAD

**Issue by mpohalos** [w0rm/gulp-svgstore#100]
As i am interested in a similar functionality of this #82 i want to ask about the following functionality.

So this svg 
`
<svg version="1.1" viewBox="0 0 100 100" class="test">
   ...
</svg>
`

is stored in the sprite as follows

`
<svg>
   <symbol id="ico-arrow-down-long">
      ...
   </symbol>
</svg>
`
I cannot pass the class of each svg to the respective symbol that is created in the sprite.
Can this be done?

**Comment by w0rm** [comment]
How did you get a class name in the svg file and what do you need this for? If the class name ends up in the browser, it then will be conflicting with the existing classes and css styles on the page. What if two icons get the same class name? I am not sure about the need to support this.
