### ISSUE TITLE
Fork or pull request for migrate to stack?

### ISSUE THREAD

**Issue by firefoxic** [w0rm/gulp-svgstore#111]
I wanted to change the code so that the plugin generates a stack sprite instead of a symbol sprite.

But the changes turned out to be very extensive, including removing the ability to inline a sprite in the markup and rewriting tests. And given that the principle of working with the plugin changes quite a lot (although it remains possible to insert external sprite icons through the `use` tag), I would like to know if such changes are of interest in the form of a pull request or does it make sense to create a full-fledged renamed fork?

**Comment by w0rm** [comment]
@firefoxic hi. I think a fork makes more sense.

**Comment by firefoxic** [comment]
Done 🚀
[gulp-stacksvg](https://github.com/firefoxic/gulp-stacksvg)
