### ISSUE TITLE
Add the sub-folder name to the symbol ID

### ISSUE THREAD

**Issue by didoo** [w0rm/gulp-svgstore#25]
If the source files are organised in folders, it would be better to add the folder name to the symbol ID.
(e.g. gulp-svgsprite uses this convention: <symbol viewBox="..." id="{folder_name}--{file_name}">

**Comment by w0rm** [comment]
@didoo just pipe your files through gulp-rename before passing to gulp-svgstore. I'm even going to remove suffix in favour of this.

**Comment by didoo** [comment]
But in some way, since is gulp-svgstore that is generating the IDs, it should be this one to take care of possible conflicts or name overlapping. Currently if you have two (or more) different files in different folders, but with the same name (e.g. /company/logo.svg and /dummy/logo.svg) the generated symbols have both "logo" or "icon-logo" as ID.

**Comment by w0rm** [comment]
I don't think it should, it clearly states that module id is based on filename.
Simple task below will produce just what you need:

src/svg/one/circle.svg -> one-circle
src/svg/one/two/three/circle.svg -> one-two-three-circle

```js
var gulp = require('gulp');
var rename = require('gulp-rename');
var svgstore = require('gulp-svgstore');

gulp.task('default', function () {
  return gulp.src('src/svg/**/*.svg', { base: 'src/svg' })
    .pipe(rename(function (path) {
      var name = path.dirname.split('/');
      name.push(path.basename);
      path.basename = name.join('-');
    }))
    .pipe(svgstore())
    .pipe(gulp.dest('dest'));
});
```

**Comment by w0rm** [comment]
@didoo I'm sorry! I just checked, and you're right about that I don't have it anywhere in the readme that icon id is generated from the file name, perhaps I should add it!

**Comment by didoo** [comment]
Mmm, sorry, don't agree :)
I totally understand your point, but since is the package that builds the ID, it should be the package that handles the logic of how to build this ID. 
For example, with the rename above, these two files will have the same ID:
`file-with-a-name.svg`
`file-with/a/name.svg`
Instead the second one should have an ID like
`file-with--a--name.svg`
Same thing if the file name contains a space, should be handled.
Same thing if the name contains a character which is not suitable for an XML ID.
And so on. Or should this be handled over and over with a rename, each one with a different implementation.
This is my suggestion, so feel free to close the issues if you don't agree, no problem.
Thanks.

**Comment by w0rm** [comment]
What if file-with--a--name.svg is also in the files? Renaming files on your own gives you more flexibility. It's up to developer to decide on the rules of how ids should be built. Gulp-svgstore can throw an error if two files have the same name.

**Comment by w0rm** [comment]
Gulp plugin [guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) say that plugin should do one thing and should not do the thing that can be done easily with another gulp plugin.

**Comment by w0rm** [comment]
@didoo I decided to keep a track of added svgs and throw an error if the same filename is added again. Plus I will update documentation with an example of using together with gulp-rename.
