### ISSUE TITLE
Reinstate prefix and filename options

### ISSUE THREAD

**Issue by SamPotts** [w0rm/gulp-svgstore#29]
It would be good to use the folder/filenames as defaults but also have the option to prefix and change the output filename. 

This seems like a step backwards.

**Comment by w0rm** [comment]
@SamPotts any reason why `.pipe(rename({prefix: 'icon-'})` is not an option for you?

**Comment by SamPotts** [comment]
Good point. I'll give that a go.

**Comment by w0rm** [comment]
@SamPotts I have documented this use case https://github.com/w0rm/gulp-svgstore#generating-id-attributes If you think its not obvious, feel free to open PR that changes Readme.

**Comment by SamPotts** [comment]
Cheers for that. I'll take a look. 

Nice work by the way!
