### ISSUE TITLE
Why cheerio is peerDependency?

### ISSUE THREAD

**Issue by TrySound** [w0rm/gulp-svgstore#34]

**Comment by w0rm** [comment]
To share the same version with gulp-cheerio because file.cheerio is cached and reused by both plugins

**Comment by TrySound** [comment]
Ok. Thanks!

**Comment by TrySound** [comment]
Maybe better leave it for user?
https://github.com/KenPowers/gulp-cheerio#breaking-changes-in-06x

**Comment by w0rm** [comment]
Ok, I only had this because of gulp-cheerio.

**Comment by TrySound** [comment]
CooL!
