### ISSUE TITLE
does not work properly with null files

### ISSUE THREAD

**Issue by tmorozov** [w0rm/gulp-svgstore#42]
version "gulp-svgstore": "~5.0.3"

error:
file.cheerio = cheerio.load(file.contents.toString(), { xmlMode: true })
TypeError: Cannot call method 'toString' of null

quick fix:
add
```javascript 
    if (file.isNull()) {
      return cb(null, file);
    }
```
before
```javascript
    if (!file.cheerio) {
      file.cheerio = cheerio.load(file.contents.toString(), { xmlMode: true })
    }
```

**Comment by w0rm** [comment]
Hi @tmorozov. A pull request with this change and a test for it is very welcome. By the way, we also dont check for the wrong file format, assuming the correct input.

**Comment by w0rm** [comment]
I also think that we should probably ignore such files and remove them from the downstream. However I'm open to discuss this matter
