### ISSUE TITLE
Copy sprites svg's attributes into symbols

### ISSUE THREAD

**Issue by ghetolay** [w0rm/gulp-svgstore#44]
So following the pull request about namespace, I think we should add the ability to copy some/all attributes from the different sprites into final symbols.

First I think namespace should be left apart and so none of the following will apply to namespace attribute.

Using a option seems the best and most flexible way to handle it for most case.
We could set an option ```copyAttr``` and cover theses values : 

- ```false``` or ```null``` (default) : Behave like now, no attributes are copied except ```viewBox```
- ```true``` : Copy all attributes
- ```array``` (white-list) : Copy attributes whose names are included in the array.
- ```function(AttrName, AttrValue, symbolId)``` : Function is called for each attribute of each sprite and return ```true``` or ```false```.

Now I don't know what to do about ```viewBox``` in the case of an array : Should it be included on the array or should it be implicitly considered into the white-list and always copied. 
IMHO it should be treated as any other attribute and then should be part of the array.

The last form using callback is handy because you can create a map to keep track of ```viewBox``` values while returning ```false``` so it won't be copied.
Here is a snippet : 
```javascript
var map = {};
gulp.src('...')
.svgstore({
    copyAttr: function(name, value, id){
        if(name == 'viewBox'){
           map[id] = value
           return false;
        }
        return true;
    }
})

//inject/update html file with the map
```

**Comment by w0rm** [comment]
Quoting @ghetolay from #41 to provide more context with this issue:

> Now what I had in mind for the project was to copy any styling attributes like ```fill```, ```stroke```, ```font-*```, etc. I mostly use ```fill``` to set the default color of the image while being able to change it with css rules when needed : see [here](http://codepen.io/anon/pen/doQmKX). This does not work on chrome, you have to use the [```currentColor``` workaround](http://codepen.io/FWeinb/blog/quick-tip-svg-use-style-two-colors) for the moment but that's the idea.
> We could avoid having attributes on svg/symbol element by adding a global surrounding ```<g>``` element and apply theses attributes on it. But I'm pretty sure you won't be able to change deep element's attribute with css when you include svg with a ```<use>`` tag. (Also this adds 6 characters !! :))

> If you want we could open a different issue to discuss about 2). We could go for a whitelist configurable by the user (override/extend) instead of a blacklist.

**Comment by thalseth** [comment]
Any updates on this @w0rm & @ghetolay ? 

I am adding width="100%" and height="100%" on every svg but these attributes are removed when using svgstore 😢

**Comment by ghetolay** [comment]
I could implement it if this is validated by @w0rm.

Right now I'm using a ```through2```, if you want to add attributes to ALL your symbols something like that  should do : 

```javascript
.pipe( svgstore() )
.pipe( through2.obj( function(file, enc, cb) {
   var $ = file.cheerio || cheerio.load(file.contents.toString(), {xmlMode:true});
   
   $('svg > symbol').each( function() {
       $(this).attr('width', '100%');
       $(this).attr('height', '100%');
   });
   
   cb(null, file);
})
```

This part : 

```javascript
file.cheerio || cheerio.load(file.contents.toString(), {xmlMode:true});
```

is safer but you'll need to add cheerio as a dependency of your project. If you call the function right after ```svgstore()```, like on the sample code, ```file.cheerio``` should always be set and you won't need this safety net.

**Comment by thalseth** [comment]
Thank you for the response @ghetolay. This is actually what i am doing now together with svgmin() to optimize each icon. It doesn't feel right to iterate over the icons again after using svgstore() to add the same attributes 😢 

```javascript
gulp.task('optimize-icons', function () {
  return gulp
    .src('src/*.svg')
    .pipe(svgmin())
    .pipe(cheerio({
        run: function ($) {
            var svg = $('svg');
            svg.attr('width','100%');
            svg.attr('height','100%');
        },
        parserOptions: { xmlMode: true }
    }))
    .pipe(gulp.dest('dist'));
});
```

**Comment by w0rm** [comment]
@thalseth I don't understand what you're trying to accomplish. Each svg becomes a symbol tag, and there is no neet to set width and height on each symbol, but rather on the use element https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol

**Comment by thalseth** [comment]
Hi @w0rm! 
I don't know why i thought my symbols should have width and height. I guess i mixed the way we work with svgs as child to an <i> element in our react components and the way we use the symbol reference. 

Thank you for this awesome package  👍

**Comment by seierstad** [comment]
@w0rm I think the preserveAspectRatio attribute should be copied from the original files svg elements to the sprite sheet symbols.

**Comment by w0rm** [comment]
Speaking on the original use-case, setting e.g. `fill` on the symbol will prevent from changing it later for the `use` tag. So I don't think this should be ever supported.

**Comment by ghetolay** [comment]
Setting `fill` on `symbol` can't be changed only on chrome.
But using `currentColor` works as you can [see here](http://codepen.io/anon/pen/bwzoZQ).

Original use case also was about not copying `viewBox` because it's useless on `symbol` tags (when used on browsers).

That being said I don't personnally need that feature anymore because now I'm inlining all svgs at load, like svg4everybody does for ie.

**Comment by w0rm** [comment]
> Setting fill on symbol can't be changed only on chrome.

Considering Chrome userbase, this means you don't really need this feature. Usually you want to get rid of all the fills and just use `currentColor`, that you can apply with simple css `symbol { fill: currentColor; }` and not copy from the original sources.

> Original use case also was about not copying viewBox because it's useless on symbol tags (when used on browsers).

[viewBox on symbol](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol) tags actually works as expected (as if you set it for the original svg). You can see it by changing the viewBox in your currentColor example.
