### ISSUE TITLE
linearGradient inside Symbol on firefox

### ISSUE THREAD

**Issue by Turqueso** [w0rm/gulp-svgstore#55]
I'm using [Inlining svgstore result into html body](https://github.com/w0rm/gulp-svgstore#inlining-svgstore-result-into-html-body) but it puts the gradient inside the symbol so it's not rendered on firefox. Is there a way so svgstore puts the gradiente outside the symbol?
The bug is on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=353575).

**Comment by w0rm** [comment]
Svgstore will extract gradient if you have it inside defs tag.

**Comment by Turqueso** [comment]
It work, thank you!

**Comment by w0rm** [comment]
@Turqueso you're welcome! Let me know if you need any other help!

**Comment by Turqueso** [comment]
@w0rm just one thing, may this should be somewhere on the docs?

**Comment by w0rm** [comment]
@Turqueso feel free to send a PR to add missing docs. For more info of what svgstore does please check the original issue https://github.com/w0rm/gulp-svgstore/issues/31
