### ISSUE TITLE
Symbols are empty after gulp-remember has populated it's cache

### ISSUE THREAD

**Issue by AndyOGo** [w0rm/gulp-svgstore#61]
I'm currently utilizing `gulp-cached` and `gulp-remember` to make my build more incremental.
Unfortunately `gulp-svgstore` is broken in conjunction with `gulp-remember`.

I tracked the issue down, to the following lines of code:

1. `gulp-svgstore` adds a JSDOM `cheerio` property to the current file, but only if it does not exist already.
[file.cheerio](https://github.com/w0rm/gulp-svgstore/blob/master/index.js#L38-L40)
2. This SVG document is cached in `$svg` [$svg](https://github.com/w0rm/gulp-svgstore/blob/master/index.js#L42)
3. At the end the whole contens of the `$svg`variable is appended to the current [SVG symbol](https://github.com/w0rm/gulp-svgstore/blob/master/index.js#L111) `$symbol`.
This step removes all children of `$svg`and hence also of `file.cheerio`, which causes empty `<symbol>` tags in my sprite after `gulp-cached` and `gulp-remember` have done their magic (e.g. after a watch has triggered).

## Suggested Fix
Cleanup file.cheerio reference in [stream._transform](https://github.com/w0rm/gulp-svgstore/blob/master/index.js#L30) function:
```js
delete file.cheerio; 
```

## Quick fix utilizing `gulp-intercept`
```js
gulp.src('src/icons/*.svg')
    .pipe($.cached('sprites:svg'))
    .pipe($.svgmin(function (file) {
        var prefix = path.basename(file.relative, path.extname(file.relative));
        return {
            plugins: [{
                cleanupIDs: {
                    prefix: prefix + '-',
                    minify: config.minifySVG
                }
            }]
        }
    }))
    .pipe($.remember('sprites:svg'))
    .pipe($.intercept(function(file) {
        // this is IMPORTANT!!!!
        // gulp-svgstore adds cheerio property to file, but does not clean up
        // hence this breaks gulp-remember, who remembers an empty cheerio instance.
        delete file.cheerio;
        return file;
    }))
    .pipe($.svgstore())
    .pipe(gulp.dest('dest/icons'))
``

**Comment by w0rm** [comment]
@AndyOGo the cached cheerio object is mentioned here: https://github.com/w0rm/gulp-svgstore#extracting-metadata-from-combined-svg
gulp-cheerio and gulp-svgstore cache it to not parse svg multiple times.

**Comment by AndyOGo** [comment]
@w0rm You are right. I think I missed to communicate the important point here.
After all children of DOM node A are appended to another DOM node B. They no longer exist in A, only in B. See [DOM Spec](https://dom.spec.whatwg.org/#dom-node-appendchild) and [MDN](https://developer.mozilla.org/de/docs/Web/API/Node/appendChild)
The cache is absolutly fine, but as soon as the children are removed, the cache loses it's children too. So it makes no sense to have an empty (dirty) cache.

**Comment by w0rm** [comment]
@AndyOGo I removed the cache completely, I think it adds more harm than benefits. Version 6.0.0 of svg-store is now published, because it may be a breaking change if someone relied on this feature.

**Comment by AndyOGo** [comment]
@w0rm Wau that was fast. Thank you.
Okay, well I think just the cache of each incoming files are proplematic. The cache of the flushed sprite should be fine (fingers crossed).

**Comment by AndyOGo** [comment]
I just came up with another possible fix. Just clone the svg before appending it to the symbol.
That way the original cache stays unchanged. (Updated above)

**Comment by w0rm** [comment]
@AndyOGo I realised that if there is a plugin that changes the content and doesn't update the cached cheerio object inbetween gulp-cheerio and gulp-svgstore, then it will break the behavior. The only possible solution would be to calculate the checksum of the content and pass it along with the cache. But it will require a lot of effort from different gulp plugins. 

Passing something along with the gulp file object seems to be a bad idea in the gulp ecosystem, I have had a lot of troubles with sourcemaps that are passed the same way.

**Comment by AndyOGo** [comment]
@w0rm I see, thats true. Then I thing it's best just avoid caching as you did already.
