### ISSUE TITLE
How to rename the generated combined svg files?

### ISSUE THREAD

**Issue by kamlekar** [w0rm/gulp-svgstore#64]
Currently when I generate using gulp, the generated file is taking the name of the source folder. But I want to rename the generated SVG file to something else.
 
Please help.

**Comment by w0rm** [comment]
Pipe the result through [gulp-rename](https://github.com/hparra/gulp-rename).

**Comment by yoggsoft** [comment]
A bit late in the conversation, but if you're not familiar with `gulp-rename`, it's just like:

```
return gulp
.src([path])
.pipe(gulpSvgStore())
.pipe(rename({ basename: 'symbols' }))
.pipe(gulp.dest([destination]));
```
