### ISSUE TITLE
Output symbols only

### ISSUE THREAD

**Issue by richardwiggins** [w0rm/gulp-svgstore#67]
I was wondering if there is anyway to just output everything as `<symbols>` (like already happens), but without the `<svg>` wrapper and initial `<defs><style>` etc?

**Comment by w0rm** [comment]
`<defs>` have to be extracted because they don't work from within a `<symbol>` , you can read more about it [here](https://github.com/w0rm/gulp-svgstore/issues/31). If you don't use `<defs>`, I guess you can pipe the result through the [gulp-cheerio](https://github.com/knpwrs/gulp-cheerio).
