### ISSUE TITLE
repaint logo in sprite

### ISSUE THREAD

**Issue by Muskos** [w0rm/gulp-svgstore#70]
I use you plugin without any setting.
I put two logo in directory:
one_logo_s2.svg
two_logo-s2.svg
And when i use your plugin, first logo repaint at color of second logo. And second logo i see normal.
Text of both logo in right color. But background of main part of first logo is wrong.
I put another few another logo. Only one logo have his color.
If i remove second logo from directory. Another logo use background color from the first logo. And etc...
Maybe something with svg?
Can you help me? What I do wrong?

**Comment by w0rm** [comment]
@Muskos can you please provide the reduced example that demonstrates your issue?

**Comment by Muskos** [comment]
https://codepen.io/Muskos/pen/RRYPzO
there are 5 logo
https://yadi.sk/i/T_sfKS3QtpkZN

**Comment by w0rm** [comment]
What i've discovered is that there are three linearGradients with the same `id="a"` that override each other. You should change this to be unique

**Comment by Muskos** [comment]
Is it a problem of svg file? I didn't rewrite code after gulp task.
I open *.ai file with all logo. All gradients named as "contour".

**Comment by w0rm** [comment]
The combined file should have unique ids. gulp-svgstore doesn't rename them, because you can use svgmin for it. In your file you ran every file though svgmin, and it has probably minified ids by renaming them to a single letter `a`.  Have you tried the usage example from the readme?

**Comment by Muskos** [comment]
i try svgmin without any options. 
thank you. all done
