### ISSUE TITLE
Removing doctype from generated sprite sheet

### ISSUE THREAD

**Issue by petebarr** [w0rm/gulp-svgstore#71]
Hi,

Just wondering if there's a way to remove the doctype and xml header from the main generated sprite sheet?

`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">`

**Comment by w0rm** [comment]
@petebarr there is an option for this `svgstore({ inlineSvg: true })`

**Comment by petebarr** [comment]
Aghhh! Sorry, I must be blind. Cheers!
