### ISSUE TITLE
Should this package be split in two?

### ISSUE THREAD

**Issue by samjarrett** [w0rm/gulp-svgstore#73]
I realised that the code in index.js is almost entirely usable without gulp, so I was wondering if it would make sense to split into a svgstore package and a gulp-svgstore wrapper, so people (like me!) can use the svgstore sans-gulp?

Thanks!

**Comment by w0rm** [comment]
Hi. I have no interest in this feature, you may want to check this discussion https://github.com/w0rm/gulp-svgstore/issues/60
