### ISSUE TITLE
<div style="height: 0; width: 0; position: absolute; visibility: hidden"> create a white box at the bottom of the page

### ISSUE THREAD

**Issue by dannypk** [w0rm/gulp-svgstore#74]
If I put top:0 manually, it disappears. Otherwise, I have an extra white box at the bottom of the page. Any idea why ? It's both firefox/chrome mobile/desktop view.
Thanks

**Comment by w0rm** [comment]
@dannypk I guess it is because an svg inside the div has bigger dimensions. Setting width and height on the div doesn't hide the overflowing content

**Comment by w0rm** [comment]
You may try to either apply the style on the svg itself, or set `overflow:hidden`.

**Comment by w0rm** [comment]
Alternatively, you may use visuallyhidden from html5 boilerplate,

https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L128


```
.visuallyhidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
    white-space: nowrap;
}
```

**Comment by RewriteH** [comment]
@w0rm it doesnt work normally with tables...
![Screenshot_1](https://user-images.githubusercontent.com/57995626/104445071-7d560700-55ba-11eb-8aa3-41aed07ff821.png)
