### ISSUE TITLE
Path concatenation example doesn't work

### ISSUE THREAD

**Issue by olabaloo** [w0rm/gulp-svgstore#75]
The example provided to concatenate relative paths, e.g. src/svg/one/two/three/circle.svg to one-two-three-circle, doesn't work.

When I print `path.sep` to the console, gulp says it is `undefined`.

Example:
```
var gulp = require('gulp');
var rename = require('gulp-rename');
var svgstore = require('gulp-svgstore');

gulp.task('default', function () {
    return gulp
        .src('src/svg/**/*.svg', { base: 'src/svg' })
        .pipe(rename(function (path) {
            console.log(path.sep);                   // undefined
            var name = path.dirname.split(path.sep);
            name.push(path.basename);
            path.basename = name.join('-');
        }))
        .pipe(svgstore())
        .pipe(gulp.dest('dest'));
});
```

**Comment by w0rm** [comment]
Hi! Sorry for the late reply, yeah, I confused `path` function argument and a `path` module that has [`path.sep`](https://nodejs.org/api/path.html#path_path_sep)

**Comment by w0rm** [comment]
I updated the Readme.
