### ISSUE TITLE
gulp-cheerio vs cheerio

### ISSUE THREAD

**Issue by kaptenw** [w0rm/gulp-svgstore#80]
Hi,

In both your [Transform svg sources or combined svg](https://github.com/w0rm/gulp-svgstore#transform-svg-sources-or-combined-svg) examples you're using [gulp-cheerio](https://github.com/KenPowers/gulp-cheerio). But in your [Extracting metadata from combined svg](https://github.com/w0rm/gulp-svgstore#extracting-metadata-from-combined-svg) example you're using the "regular" [cheerio](https://github.com/cheeriojs/cheerio).

Is there a way to use your [Extracting metadata from combined svg](https://github.com/w0rm/gulp-svgstore#extracting-metadata-from-combined-svg) with [gulp-cheerio](https://github.com/KenPowers/gulp-cheerio)?

The reason I'm asking is because I used [gulp-cheerio](https://github.com/KenPowers/gulp-cheerio) together with gulp-svgstore earlier, but it broke with the release of gulp-svgstore 6.0.0, and now it only works with [cheerio](https://github.com/cheeriojs/cheerio).

**Comment by w0rm** [comment]
@kaptenw can you setup a small example project that reproduces the issue with gulp-cheerio?
