### ISSUE TITLE
"viewBox → viewbox" is bad

### ISSUE THREAD

**Issue by nicothin** [w0rm/gulp-svgstore#83]
Bringing attributes to the lower case causes problems with resizing svg>use
![image](https://cloud.githubusercontent.com/assets/3499680/26524128/01a36448-4332-11e7-9951-aa0f12147b2e.png)

If the attribute `viewBox` is written in lowercase, the resizing of the icon does not work

**Comment by w0rm** [comment]
Hi @nicothin! I'm not sure what is the issue, because `gulp-svgstore` doesn't rename viewBox to lowercase.

**Comment by nicothin** [comment]
Sorry
This is the fault of cheerio.

**Comment by w0rm** [comment]
@nicothin oh, you probably need `parserOptions: { xmlMode: true }` there

**Comment by nicothin** [comment]
@w0rm TNX!!!

**Comment by francescostella** [comment]
For posterity and everyone reference here how to structure the options object, based on @w0rm solution:
```js
.pipe(cheerio({
  run: function ($) {
    $('svg').attr('style',  'display:none');
  },
  parserOptions: { xmlMode: true }
}))
```
