### ISSUE TITLE
<def><style> stops fill: anycolor

### ISSUE THREAD

**Issue by w3debugger** [w0rm/gulp-svgstore#84]
I'm was trying to add color to icons but because of the `<defs><style>.a{fill:#666}</style>` I was unable to modify color. There should be a way to remove `<defs></defs>` after combining svg files.

**Comment by w0rm** [comment]
@w3debugger having style tags in svg icons is a bad idea, because all styles end up in the combined file, and may override each other.

**Comment by w3debugger** [comment]
I'm removing `<def><style>` manually after runny `gulp svgstore`. This  should be added in the script not manually. @w0rm

**Comment by w0rm** [comment]
It should not be added to the script, because this may result in damaged/improperly styled icons that depend on the styles. Icons with `<style>` should not be used with this method.
