### ISSUE TITLE
Defs cleanup?? Defs are missing after running svgstore

### ISSUE THREAD

**Issue by KingScooty** [w0rm/gulp-svgstore#86]
I'm noticing all my svg's are getting stripped of their `<def>` tags at the svgstore step. Is `gulp-svgstore` doing any <def> cleanup? How do i turn it off?

I've tried using:
```
.pipe(svgstore({
    cleanupdefs: false
}))
```

But i'm still having the problem.

Any ideas?

**Comment by w0rm** [comment]
[defs must be outside the symbol](https://github.com/w0rm/gulp-svgstore/issues/31) there's nothing we can do about this.
