### ISSUE TITLE
gulp4 alpha.3

### ISSUE THREAD

**Issue by jonnitto** [w0rm/gulp-svgstore#87]
If I run your plugin with gulp4 I got following error: `file.isSymbolic is not a function` It has to do with `vinyl-fs` version 3

**Comment by saki007ster** [comment]
@jonnitto this is happening because gulp4 alpha.3 does not vinyl ^2.0 you might need to upgrade to vinyl ^2.1 also STOP using `gulp-util` - check - https://github.com/gulpjs/gulp/issues/2065

**Comment by phated** [comment]
@saki007ster yep, this is using an insanely old Vinyl. It needs to stop using gulp-util (now deprecated) and use vinyl directly.

**Comment by w0rm** [comment]
@phated if I update the plugin to use the lasted vinyl, will this still work with the old gulp?
