### ISSUE TITLE
Moving away from the Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [w0rm/gulp-svgstore#93]
`new Buffer(...)` is deprecated and unsafe. Would it be possible to use `Buffer.from(...)` in the [relevant places](https://github.com/w0rm/gulp-svgstore/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) instead?

**Comment by w0rm** [comment]
I’m not sure. This would require dropping 0.12 support.

**Comment by w0rm** [comment]
Released 7.0.0 that stops using `new Buffer()`
