### ISSUE TITLE
Content loaded via ajax shows empty icons

### ISSUE THREAD

**Issue by matthewnessworthy** [w0rm/gulp-svgstore#94]
With relation to https://stackoverflow.com/questions/44245032/svg-symbols-not-loading-with-ajax-content-in-chrome

Please can you include `xmlns:xlink="http://www.w3.org/1999/xlink"` in the `<svg/>` tag definition.

Currently when content containing is loaded via ajax, icons within the content are blank.

**Comment by w0rm** [comment]
@matthewnessworthy can you open a PR that adds it here: https://github.com/w0rm/gulp-svgstore/blob/master/index.js#L18 and updates the tests?

**Comment by w0rm** [comment]
@matthewnessworthy thanks! Just published 7.0.1. I'm not sure what's happened to the usage tests
