### ISSUE TITLE
No preview files available

### ISSUE THREAD

**Issue by prajith-ta** [w0rm/gulp-svgstore#99]
Please add a preview file for sprites like gulp-svg-sprites.

**Comment by w0rm** [comment]
I think generating previews from a bunch of svgs should be its own gulp plugin! 

According to https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md 

> Your plugin should only do one thing, and do it well.
> Avoid config options that make your plugin do completely different tasks
